# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted
steps:
- task: CopyFiles@2
  displayName: 'Copy Files (2) to: $(Build.BinariesDirectory)'
  inputs:
    Contents: README.md
    TargetFolder: '$(Build.BinariesDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)'
    artifactName: 'drop2'
